[package]
name = "openkey-protocols"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Protocolos CTAP2, CBOR, HID e WebAuthn do OpenKey (no_std)"

[dependencies]
openkey-core = { workspace = true }
openkey-crypto = { workspace = true }
heapless = { version = "0.8.0", default-features = false }
zeroize = { version = "1.8.2", default-features = false }

[features]
default = []

[dev-dependencies]
hex = "0.4"

