[package]
name = "openkey-crypto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Abstrações criptográficas do OpenKey (no_std)"

[dependencies]
aes-gcm = { version = "0.11.0", default-features = false, features = ["aes"] }

[features]
default = []
