[package]
name = "openkey-usb"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Camada de transporte USB HID do OpenKey (no_std)"

[dependencies]
openkey-platform = { workspace = true }

[features]
default = []
