[package]
name = "openkey-simulator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Simulador de Software em Host/Desktop para o OpenKey Framework"

[dependencies]
openkey-core = { workspace = true }
openkey-pal = { workspace = true }

[features]
default = []
